################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../HAL_Driver/Src/stm32l4xx_hal.c \
../HAL_Driver/Src/stm32l4xx_hal_adc.c \
../HAL_Driver/Src/stm32l4xx_hal_adc_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_can.c \
../HAL_Driver/Src/stm32l4xx_hal_comp.c \
../HAL_Driver/Src/stm32l4xx_hal_cortex.c \
../HAL_Driver/Src/stm32l4xx_hal_crc.c \
../HAL_Driver/Src/stm32l4xx_hal_crc_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_cryp.c \
../HAL_Driver/Src/stm32l4xx_hal_cryp_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_dac.c \
../HAL_Driver/Src/stm32l4xx_hal_dac_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_dcmi.c \
../HAL_Driver/Src/stm32l4xx_hal_dfsdm.c \
../HAL_Driver/Src/stm32l4xx_hal_dfsdm_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_dma.c \
../HAL_Driver/Src/stm32l4xx_hal_dma2d.c \
../HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_dsi.c \
../HAL_Driver/Src/stm32l4xx_hal_firewall.c \
../HAL_Driver/Src/stm32l4xx_hal_flash.c \
../HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
../HAL_Driver/Src/stm32l4xx_hal_gfxmmu.c \
../HAL_Driver/Src/stm32l4xx_hal_gpio.c \
../HAL_Driver/Src/stm32l4xx_hal_hash.c \
../HAL_Driver/Src/stm32l4xx_hal_hash_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_hcd.c \
../HAL_Driver/Src/stm32l4xx_hal_i2c.c \
../HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_irda.c \
../HAL_Driver/Src/stm32l4xx_hal_iwdg.c \
../HAL_Driver/Src/stm32l4xx_hal_lcd.c \
../HAL_Driver/Src/stm32l4xx_hal_lptim.c \
../HAL_Driver/Src/stm32l4xx_hal_ltdc.c \
../HAL_Driver/Src/stm32l4xx_hal_ltdc_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_msp_template.c \
../HAL_Driver/Src/stm32l4xx_hal_nand.c \
../HAL_Driver/Src/stm32l4xx_hal_nor.c \
../HAL_Driver/Src/stm32l4xx_hal_opamp.c \
../HAL_Driver/Src/stm32l4xx_hal_opamp_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_ospi.c \
../HAL_Driver/Src/stm32l4xx_hal_pcd.c \
../HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_pwr.c \
../HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_qspi.c \
../HAL_Driver/Src/stm32l4xx_hal_rcc.c \
../HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_rng.c \
../HAL_Driver/Src/stm32l4xx_hal_rtc.c \
../HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_sai.c \
../HAL_Driver/Src/stm32l4xx_hal_sai_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_sd.c \
../HAL_Driver/Src/stm32l4xx_hal_sd_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_smartcard.c \
../HAL_Driver/Src/stm32l4xx_hal_smartcard_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_smbus.c \
../HAL_Driver/Src/stm32l4xx_hal_spi.c \
../HAL_Driver/Src/stm32l4xx_hal_spi_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_sram.c \
../HAL_Driver/Src/stm32l4xx_hal_swpmi.c \
../HAL_Driver/Src/stm32l4xx_hal_tim.c \
../HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_timebase_tim_template.c \
../HAL_Driver/Src/stm32l4xx_hal_tsc.c \
../HAL_Driver/Src/stm32l4xx_hal_uart.c \
../HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_usart.c \
../HAL_Driver/Src/stm32l4xx_hal_usart_ex.c \
../HAL_Driver/Src/stm32l4xx_hal_wwdg.c \
../HAL_Driver/Src/stm32l4xx_ll_adc.c \
../HAL_Driver/Src/stm32l4xx_ll_comp.c \
../HAL_Driver/Src/stm32l4xx_ll_crc.c \
../HAL_Driver/Src/stm32l4xx_ll_crs.c \
../HAL_Driver/Src/stm32l4xx_ll_dac.c \
../HAL_Driver/Src/stm32l4xx_ll_dma.c \
../HAL_Driver/Src/stm32l4xx_ll_dma2d.c \
../HAL_Driver/Src/stm32l4xx_ll_exti.c \
../HAL_Driver/Src/stm32l4xx_ll_fmc.c \
../HAL_Driver/Src/stm32l4xx_ll_gpio.c \
../HAL_Driver/Src/stm32l4xx_ll_i2c.c \
../HAL_Driver/Src/stm32l4xx_ll_lptim.c \
../HAL_Driver/Src/stm32l4xx_ll_lpuart.c \
../HAL_Driver/Src/stm32l4xx_ll_opamp.c \
../HAL_Driver/Src/stm32l4xx_ll_pwr.c \
../HAL_Driver/Src/stm32l4xx_ll_rcc.c \
../HAL_Driver/Src/stm32l4xx_ll_rng.c \
../HAL_Driver/Src/stm32l4xx_ll_rtc.c \
../HAL_Driver/Src/stm32l4xx_ll_sdmmc.c \
../HAL_Driver/Src/stm32l4xx_ll_spi.c \
../HAL_Driver/Src/stm32l4xx_ll_swpmi.c \
../HAL_Driver/Src/stm32l4xx_ll_tim.c \
../HAL_Driver/Src/stm32l4xx_ll_usart.c \
../HAL_Driver/Src/stm32l4xx_ll_usb.c \
../HAL_Driver/Src/stm32l4xx_ll_utils.c 

OBJS += \
./HAL_Driver/Src/stm32l4xx_hal.o \
./HAL_Driver/Src/stm32l4xx_hal_adc.o \
./HAL_Driver/Src/stm32l4xx_hal_adc_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_can.o \
./HAL_Driver/Src/stm32l4xx_hal_comp.o \
./HAL_Driver/Src/stm32l4xx_hal_cortex.o \
./HAL_Driver/Src/stm32l4xx_hal_crc.o \
./HAL_Driver/Src/stm32l4xx_hal_crc_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_cryp.o \
./HAL_Driver/Src/stm32l4xx_hal_cryp_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_dac.o \
./HAL_Driver/Src/stm32l4xx_hal_dac_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_dcmi.o \
./HAL_Driver/Src/stm32l4xx_hal_dfsdm.o \
./HAL_Driver/Src/stm32l4xx_hal_dfsdm_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_dma.o \
./HAL_Driver/Src/stm32l4xx_hal_dma2d.o \
./HAL_Driver/Src/stm32l4xx_hal_dma_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_dsi.o \
./HAL_Driver/Src/stm32l4xx_hal_firewall.o \
./HAL_Driver/Src/stm32l4xx_hal_flash.o \
./HAL_Driver/Src/stm32l4xx_hal_flash_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.o \
./HAL_Driver/Src/stm32l4xx_hal_gfxmmu.o \
./HAL_Driver/Src/stm32l4xx_hal_gpio.o \
./HAL_Driver/Src/stm32l4xx_hal_hash.o \
./HAL_Driver/Src/stm32l4xx_hal_hash_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_hcd.o \
./HAL_Driver/Src/stm32l4xx_hal_i2c.o \
./HAL_Driver/Src/stm32l4xx_hal_i2c_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_irda.o \
./HAL_Driver/Src/stm32l4xx_hal_iwdg.o \
./HAL_Driver/Src/stm32l4xx_hal_lcd.o \
./HAL_Driver/Src/stm32l4xx_hal_lptim.o \
./HAL_Driver/Src/stm32l4xx_hal_ltdc.o \
./HAL_Driver/Src/stm32l4xx_hal_ltdc_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_msp_template.o \
./HAL_Driver/Src/stm32l4xx_hal_nand.o \
./HAL_Driver/Src/stm32l4xx_hal_nor.o \
./HAL_Driver/Src/stm32l4xx_hal_opamp.o \
./HAL_Driver/Src/stm32l4xx_hal_opamp_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_ospi.o \
./HAL_Driver/Src/stm32l4xx_hal_pcd.o \
./HAL_Driver/Src/stm32l4xx_hal_pcd_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_pwr.o \
./HAL_Driver/Src/stm32l4xx_hal_pwr_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_qspi.o \
./HAL_Driver/Src/stm32l4xx_hal_rcc.o \
./HAL_Driver/Src/stm32l4xx_hal_rcc_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_rng.o \
./HAL_Driver/Src/stm32l4xx_hal_rtc.o \
./HAL_Driver/Src/stm32l4xx_hal_rtc_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_sai.o \
./HAL_Driver/Src/stm32l4xx_hal_sai_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_sd.o \
./HAL_Driver/Src/stm32l4xx_hal_sd_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_smartcard.o \
./HAL_Driver/Src/stm32l4xx_hal_smartcard_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_smbus.o \
./HAL_Driver/Src/stm32l4xx_hal_spi.o \
./HAL_Driver/Src/stm32l4xx_hal_spi_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_sram.o \
./HAL_Driver/Src/stm32l4xx_hal_swpmi.o \
./HAL_Driver/Src/stm32l4xx_hal_tim.o \
./HAL_Driver/Src/stm32l4xx_hal_tim_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_timebase_tim_template.o \
./HAL_Driver/Src/stm32l4xx_hal_tsc.o \
./HAL_Driver/Src/stm32l4xx_hal_uart.o \
./HAL_Driver/Src/stm32l4xx_hal_uart_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_usart.o \
./HAL_Driver/Src/stm32l4xx_hal_usart_ex.o \
./HAL_Driver/Src/stm32l4xx_hal_wwdg.o \
./HAL_Driver/Src/stm32l4xx_ll_adc.o \
./HAL_Driver/Src/stm32l4xx_ll_comp.o \
./HAL_Driver/Src/stm32l4xx_ll_crc.o \
./HAL_Driver/Src/stm32l4xx_ll_crs.o \
./HAL_Driver/Src/stm32l4xx_ll_dac.o \
./HAL_Driver/Src/stm32l4xx_ll_dma.o \
./HAL_Driver/Src/stm32l4xx_ll_dma2d.o \
./HAL_Driver/Src/stm32l4xx_ll_exti.o \
./HAL_Driver/Src/stm32l4xx_ll_fmc.o \
./HAL_Driver/Src/stm32l4xx_ll_gpio.o \
./HAL_Driver/Src/stm32l4xx_ll_i2c.o \
./HAL_Driver/Src/stm32l4xx_ll_lptim.o \
./HAL_Driver/Src/stm32l4xx_ll_lpuart.o \
./HAL_Driver/Src/stm32l4xx_ll_opamp.o \
./HAL_Driver/Src/stm32l4xx_ll_pwr.o \
./HAL_Driver/Src/stm32l4xx_ll_rcc.o \
./HAL_Driver/Src/stm32l4xx_ll_rng.o \
./HAL_Driver/Src/stm32l4xx_ll_rtc.o \
./HAL_Driver/Src/stm32l4xx_ll_sdmmc.o \
./HAL_Driver/Src/stm32l4xx_ll_spi.o \
./HAL_Driver/Src/stm32l4xx_ll_swpmi.o \
./HAL_Driver/Src/stm32l4xx_ll_tim.o \
./HAL_Driver/Src/stm32l4xx_ll_usart.o \
./HAL_Driver/Src/stm32l4xx_ll_usb.o \
./HAL_Driver/Src/stm32l4xx_ll_utils.o 

C_DEPS += \
./HAL_Driver/Src/stm32l4xx_hal.d \
./HAL_Driver/Src/stm32l4xx_hal_adc.d \
./HAL_Driver/Src/stm32l4xx_hal_adc_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_can.d \
./HAL_Driver/Src/stm32l4xx_hal_comp.d \
./HAL_Driver/Src/stm32l4xx_hal_cortex.d \
./HAL_Driver/Src/stm32l4xx_hal_crc.d \
./HAL_Driver/Src/stm32l4xx_hal_crc_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_cryp.d \
./HAL_Driver/Src/stm32l4xx_hal_cryp_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_dac.d \
./HAL_Driver/Src/stm32l4xx_hal_dac_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_dcmi.d \
./HAL_Driver/Src/stm32l4xx_hal_dfsdm.d \
./HAL_Driver/Src/stm32l4xx_hal_dfsdm_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_dma.d \
./HAL_Driver/Src/stm32l4xx_hal_dma2d.d \
./HAL_Driver/Src/stm32l4xx_hal_dma_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_dsi.d \
./HAL_Driver/Src/stm32l4xx_hal_firewall.d \
./HAL_Driver/Src/stm32l4xx_hal_flash.d \
./HAL_Driver/Src/stm32l4xx_hal_flash_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.d \
./HAL_Driver/Src/stm32l4xx_hal_gfxmmu.d \
./HAL_Driver/Src/stm32l4xx_hal_gpio.d \
./HAL_Driver/Src/stm32l4xx_hal_hash.d \
./HAL_Driver/Src/stm32l4xx_hal_hash_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_hcd.d \
./HAL_Driver/Src/stm32l4xx_hal_i2c.d \
./HAL_Driver/Src/stm32l4xx_hal_i2c_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_irda.d \
./HAL_Driver/Src/stm32l4xx_hal_iwdg.d \
./HAL_Driver/Src/stm32l4xx_hal_lcd.d \
./HAL_Driver/Src/stm32l4xx_hal_lptim.d \
./HAL_Driver/Src/stm32l4xx_hal_ltdc.d \
./HAL_Driver/Src/stm32l4xx_hal_ltdc_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_msp_template.d \
./HAL_Driver/Src/stm32l4xx_hal_nand.d \
./HAL_Driver/Src/stm32l4xx_hal_nor.d \
./HAL_Driver/Src/stm32l4xx_hal_opamp.d \
./HAL_Driver/Src/stm32l4xx_hal_opamp_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_ospi.d \
./HAL_Driver/Src/stm32l4xx_hal_pcd.d \
./HAL_Driver/Src/stm32l4xx_hal_pcd_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_pwr.d \
./HAL_Driver/Src/stm32l4xx_hal_pwr_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_qspi.d \
./HAL_Driver/Src/stm32l4xx_hal_rcc.d \
./HAL_Driver/Src/stm32l4xx_hal_rcc_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_rng.d \
./HAL_Driver/Src/stm32l4xx_hal_rtc.d \
./HAL_Driver/Src/stm32l4xx_hal_rtc_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_sai.d \
./HAL_Driver/Src/stm32l4xx_hal_sai_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_sd.d \
./HAL_Driver/Src/stm32l4xx_hal_sd_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_smartcard.d \
./HAL_Driver/Src/stm32l4xx_hal_smartcard_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_smbus.d \
./HAL_Driver/Src/stm32l4xx_hal_spi.d \
./HAL_Driver/Src/stm32l4xx_hal_spi_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_sram.d \
./HAL_Driver/Src/stm32l4xx_hal_swpmi.d \
./HAL_Driver/Src/stm32l4xx_hal_tim.d \
./HAL_Driver/Src/stm32l4xx_hal_tim_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_timebase_tim_template.d \
./HAL_Driver/Src/stm32l4xx_hal_tsc.d \
./HAL_Driver/Src/stm32l4xx_hal_uart.d \
./HAL_Driver/Src/stm32l4xx_hal_uart_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_usart.d \
./HAL_Driver/Src/stm32l4xx_hal_usart_ex.d \
./HAL_Driver/Src/stm32l4xx_hal_wwdg.d \
./HAL_Driver/Src/stm32l4xx_ll_adc.d \
./HAL_Driver/Src/stm32l4xx_ll_comp.d \
./HAL_Driver/Src/stm32l4xx_ll_crc.d \
./HAL_Driver/Src/stm32l4xx_ll_crs.d \
./HAL_Driver/Src/stm32l4xx_ll_dac.d \
./HAL_Driver/Src/stm32l4xx_ll_dma.d \
./HAL_Driver/Src/stm32l4xx_ll_dma2d.d \
./HAL_Driver/Src/stm32l4xx_ll_exti.d \
./HAL_Driver/Src/stm32l4xx_ll_fmc.d \
./HAL_Driver/Src/stm32l4xx_ll_gpio.d \
./HAL_Driver/Src/stm32l4xx_ll_i2c.d \
./HAL_Driver/Src/stm32l4xx_ll_lptim.d \
./HAL_Driver/Src/stm32l4xx_ll_lpuart.d \
./HAL_Driver/Src/stm32l4xx_ll_opamp.d \
./HAL_Driver/Src/stm32l4xx_ll_pwr.d \
./HAL_Driver/Src/stm32l4xx_ll_rcc.d \
./HAL_Driver/Src/stm32l4xx_ll_rng.d \
./HAL_Driver/Src/stm32l4xx_ll_rtc.d \
./HAL_Driver/Src/stm32l4xx_ll_sdmmc.d \
./HAL_Driver/Src/stm32l4xx_ll_spi.d \
./HAL_Driver/Src/stm32l4xx_ll_swpmi.d \
./HAL_Driver/Src/stm32l4xx_ll_tim.d \
./HAL_Driver/Src/stm32l4xx_ll_usart.d \
./HAL_Driver/Src/stm32l4xx_ll_usb.d \
./HAL_Driver/Src/stm32l4xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
HAL_Driver/Src/%.o: ../HAL_Driver/Src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32 -DSTM32L4 -DSTM32L476RGTx -DNUCLEO_L476RG -DDEBUG -DSTM32L476xx -DUSE_HAL_DRIVER -I"C:/Users/Eason/workspace/timegloves/HAL_Driver/Inc/Legacy" -I"C:/Users/Eason/workspace/timegloves/inc" -I"C:/Users/Eason/workspace/timegloves/CMSIS/device" -I"C:/Users/Eason/workspace/timegloves/CMSIS/core" -I"C:/Users/Eason/workspace/timegloves/HAL_Driver/Inc" -I"C:/Users/Eason/workspace/timegloves/Utilities/STM32L4xx_Nucleo" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


